== Chapter I

I was born in the parish of Longham, in the county of Norfolk, the 1st of first month,
1652, of reputable parents.
My mother had nine children, of whom I was the seventh;
my father died when I was so young that I can remember little of him.

My mother was left a very sorrowful widow, with all her nine children at home,
and a considerable farm to manage; and troublesome times through an unsettled government,
made things still more difficult to her,
yet she continued in that station for some years; but we growing up,
and having been brought up to business, and our mother inclining to a more retired life,
she, by the advice of several with whom she was intimately acquainted,
pursued her intention, and after deliberate consideration, disposed of her effects.
Those of us who were grown up and fit for service, were,
by the advice and concurrence of our dear mother, put into reputable places,
three of the youngest still continuing at home under her care and instruction.
She was very careful to teach us to read and write,
and did not fail to inculcate the principles of religion;
for she was a very pious and religious woman, was well educated in her youth,
both as to writing and literature, and in other things relating to her sex,
exceeded many.

She was daughter of a clergyman whose name was Thomas Green,
he had the benefice of Royston, in Hertfordshire, where he lived and died,
being a man of no small repute, and at his death was much lamented by his parishoners.
I coming to that town, several of the ancient inhabitants, hearing whose grandson I was,
came to pay me a visit, and in giving a relation of my grandfather,
wept at the remembrance of him, saying, he was a very pious man,
and never extorted anything from his hearers,
but accepted what they would freely give him.

My dear mother, though always brought up in that way,
after the beheading of king Charles I., when other teachers were introduced,
declined going to hear them, although much sought to by them.
She would often tell us,
that she saw so much deceit and hypocrisy covered under the pretence of religion,
that she could not by any means join with them;
but did believe the Lord would raise up a people who would be more agreeable to his will.
She waited to come to the knowledge of these,
and would sometimes be hinting at a people that were come forth,
who were great sufferers for their religion;
and said she did not know but these might be those whom God had raised up,
to stain the beauty of the pictures of those feigned religions,
that were so much then in vogue.
These were the people called Quakers, of whom she had yet but little knowledge.

Hearing there was one of them lived about six miles from her,
she had a desire to pay him a visit; she knew him before he was called by that name,
and he also had some knowledge of her.
Accordingly one day she took me to ride before her,
and entering into some discourse with him, she being a wise woman,
quickly found his zeal to over-run his knowledge,
which opportunity proved rather to her hurt than benefit.
She stayed not long, I being still on horseback, but presently mounted,
and we had not rode far before I perceived she was under some uneasiness,
intimating she had met with a disappointment in what she expected.

After king Charles`' restoration, she observed that the clergy,
who had turned to be Nonconformists, now returned to be Conformists again;
from which she concluded,
that rewards and benefices were more in their view than the solid part of religion;
so that she continued in a retired way of life for a considerable time afterwards.
But hearing of the continual sufferings of the people called Quakers,
it raised a stronger belief in her,
that they were come to the knowledge of a Divine principle,
which so powerfully supported them in the time of their affliction;
and she grew more desirous of some conversation with that people;
in order to which she inclined to remove to the city of Norwich,
where I shall at present leave her,
but shall have occasion to make mention of her hereafter.

When I was between eleven and twelve years of age,
I was much given to divert myself in running, wrestling and foot-ball playing,
which was much practised in the part of the country where I lived,
and my company was very much desired by such.
But my good mother, whose care was continually over her children for their good,
would often drop some words that tended to lead us to a more serious way of life,
which had often the desired effect,
preserving us from that profane way which too many fell into,
both in their words and conduct, to the great dishonour of God and true religion.

Being one day by myself, not far from the place of our habitation,
I met with such a visitation, as I had been altogether ignorant of before,
in which a sweet calmness spread over my mind; and it rose in my heart,
that if I could but keep to this, what might I grow up to in time?
It much affected me, and rested with me for some time,
and I acquainted my mother therewith.
She greatly rejoiced at it, and encouraged me to retire to it;
and I then had a full intention to do so.
And when my companions got about me, pressing me to do as I used to do,
although I had some inclination to answer their desires,
I found something in me that laid a restraint upon me,
and prevented me from complying with their solicitations.
But through continual importunities, and a natural inclination to a spirit of liberty,
I came by degrees to lose much of the sense of that visitation, which now and then,
upon serious reflection, caused me greatly to mourn for the loss I had sustained.
Through often gratifying my youthful desires,
and going from the instruction of my inward guide,
I found a gradual decay as to religion to attend,
even until at length I came to be left to myself.

I was now between twelve and thirteen years old, and inclined to go to some trade,
which my mother encouraged, but acquainted me, that it must be to some handicraft;
for she considered that it would be imprudent to put me to any business,
in which a stock would be needed to set me up when I came out of my time.
For although she had something to support herself,
yet having four sons and five daughters,
none of them could depend upon receiving much from her.
We were all of us pretty well brought up, both in reading and writing;
and although we who were the younger were most behind,
yet we were able to signify our minds one to another by our pens.

My mother desired me to acquaint her what trade I most inclined to.
I told her I was willing to go to any, and at last concluded to be a shoemaker, saying,
I thought it would take but little to put me out,
and I should have something wherewith to get my livelihood.
She commended my thought, and there being one about a mile from our house,
who had then a pretty fair character, we applied to him.
He readily embraced the proposal, and I was bound to him for five years,
and five pounds was paid to him.
But it happened we were mistaken in my master`'s circumstances;
for before I had been with him, I believe, a whole year,
he in a private manner informed me that he was got into debt,
and had not sufficient to answer his creditors; and being afraid of imprisonment,
had no other way to escape it but to go off; and told me if I would go along with him,
he would take as much care of me as of himself, desiring me to keep this secret;
and if I inclined to go, he would have me take leave of my mother,
but to be sure to conceal our intentions.

This was indeed a very hard pinch upon me; but I considered that five pounds were gone,
and I little the better for it, and so it was better for me to embrace the offer.
He having a brother of the same vocation, we all concluded to go together;
and I went and took leave of my mother.
But my parting with her was with great reluctance, and she said to me, "`Child,
it will not be long before I shall see you again;`" so with a heart very full I returned.

The next night about twelve o`'clock we set out,
and got the night following within a mile of Edmundsbury in Suffolk:
the next day we came to that town, and having but little money with us,
we sat down there to work.
Our stay was not long before we made our way for London;
at which place we arrived in about three days,
it being soon after the great fire in 1666.
The city lay as a heap of rubbish, and all hands at work;
for they flocked up out of the country from all parts, there being work enough for all.
My master and his brother fell presently into work, but I was fit for little there,
and to live and do nothing was very uneasy to me.
We three dwelt together in the name of brothers, and my master stood in some fear of me,
lest I should make a discovery, although I was no ways inclinable to it;
so I took an opportunity to tell him, it would neither do him nor me any good,
for me to live after that manner doing nothing,
and said if we could find a good workman of his own trade,
I did not doubt but he would take me for a time.

It was not long before we found such a one, who, upon seeing me,
was very willing to take me; so to him I went,
and stayed with him three years or something more,
in which time I understood my business pretty well,
and was a little ambitious in my mind to become master of it.
After I left him, I got into the company of the best workmen,
which caused me to spend what I got among them, although I then earned considerable.

A short time before I left my place, a very hot persecution began against the dissenters.
I then dwelt in Stepney parish, not very far from Ratcliff meetinghouse,
belonging to the people called Quakers.
Sir John Robinson was then lieutenant of the Tower,
and being a person maliciously bent against the said people,
he one day sent a company of his soldiers with orders to break into the said meetinghouse,
and to take out what seats, etc. they could find, and burn them.
Soon after this, he, with another justice of Stepney parish,
concluded to come and break up their meeting on a first-day.
Upon this account the militia was raised,
and some companies of foot also came from the tower,
and a great many wardsmen were ordered to appear armed with halberts,
among whom I was one, not by inclination, but by order of my master;
although indeed I had a secret desire to see what would be done.
Besides these forces there came a multitude of spectators.
Some of the last came in love,
to see if they could in any way be serviceable to the sufferers,
and others were evilly inclined to get what they could from them.

Those who appeared in arms had orders to let all the Quakers come in that would,
but to allow none to go out until the justices came; who, when they approached,
treated the Quakers with very rough language, calling them rogues and rebels,
for meeting there contrary to law, and began to take their names.
After this was done, they were permitted to go out,
and they not pulling off their hats to the justices,
the rude people in the yard plucked them off, and threw them over the wall;
but they who were friends to them saved what they could, and restored them to the owners;
others who had a mind to make a prey, got a good hat and left a bad one.

Sir John took a distaste against three of the said people, I think,
for something they said to him,
and ordered a court order to be made to send them to New-prison.
The warrant and prisoners being committed to the care of the constable to convey there,
he ran about to find some wardsmen to assist him, when all were gone but me and one more;
and in our way the prisoners made a stop in White-chapel, by the leave of the constable,
to get some refreshment and to take a copy of the warrant.
While we were there, one of them came to me and said, "`You have an innocent countenance,
and do not look like a persecutor.`"
I said "`No, it was much contrary to my inclination;`" they then answered,
"`We believe you, and freely forgive you.`"
This had an effect upon me, and begot some tenderness in my heart towards them.

It was late before we delivered them to the keeper, who said,
I know not what to do with them;
several others being brought to him from other parts of the city that day.
When we returned back it was late,
and passing through Ratcliff-highway the watchmen seized and examined us,
and threatened to put us into the Round-house, for being out at that time of the night;
but the constable acquainting them with the reason of it, they let us pass.
It was but a few days after this,
that several soldiers were sent from the Tower to pull down the said meetinghouse,
of which they made very ruinous work.

Although I was now in a loose way of living,
yet I had some secret touches of that which was good,
which raised a desire in me to go to some religious meetings,
but cannot say that I got much benefit thereby;
for liberty was still most grateful to me.
But the good example I had in my childhood did all along rest with me,
by which I was preserved from the profane way of life,
that was too much practised in those times as well as now.

My worthy mother, who now resided at Norwich,
had conversation with the people called Quakers,
of whom she entertained so good an opinion before;
and being thoroughly satisfied that they had found what she needed,
she readily embraced the principles they professed,
and sat down with great satisfaction in their meetings.
Three of her children, who about this time lived with her,
were also convinced of the Truth,
and they lived in a great deal of love and unity one with another.
Being fully satisfied, that she was come to the ground and foundation of true religion,
she became very much concerned for the rest of her children,
and being ready with her pen,
wrote to acquaint them that she had met with what she had long wanted;
and among the rest she remembered me,
and wrote to acquaint me with what people she had joined herself,
as well as those children then with her;
and there being so many good opportunities in the city of London,
she said she should be glad to hear that I frequented their assemblies;
with other words relating thereto.
I quartered then in Pall-mall, not far from the court.

My companion then was a pretty sober young man,
who professed himself to be a Presbyterian,
with whom I was sometimes a little too jocular in a bantering way.
He was with me when the letter came to my hands, which I read to myself;
but coming to the words that advised me to go to the Quakers`' meetings,
the evil-nature got up in me,
and put me into such a passion that I could read no further,
but put the letter into my pocket.

This was on the sixth-day of the week, and I think in the year 1671.
The first-day following, after I had dined,
I went to take a walk under the arches in Covent-garden,
and after a little time a solid concern came over my mind, and this arose in my thoughts,
"`What is the matter that you cannot read your mother`'s letter?`"
With that I went and sat down on a large stone that was prepared for a building,
and read the letter with pleasure, and it arose in my mind to go to a meeting.
The enemy of all righteousness suggested to me,
"`You know not where a meeting is;`" but it very intelligibly opened on my understanding,
"`Go down to Charing-cross, and there you shall see some of that people, follow them.`"

Upon this I arose and went down the Haymarket near to Charing-cross,
and there I saw five or six of the said people;
which was a confirmation to me that the opening was right.
So I followed them at some distance, and their habit, with their solid behaviour,
affected me.
They were going to the meeting at Westminster, and when they came there they went in,
but I stood at the door for awhile.
Here the enemy was at work again, and would have persuaded me to go away, intimating,
that if some of my old acquaintance came, they would but laugh at me;
but the better part prevailed.

The meeting was then kept in two parts,
there being shutters to open into the dwelling-house to enlarge it upon occasion;
and I seeing a post in the further room, thought if I got behind that,
and any person came to the first door they could not see me; so there I went accordingly,
and the meeting, I think, was not then much above half gathered.
Abundance of reasoning now entered into my mind,
and the enemy was hard at work to beget a belief in me,
that if any one stood up to speak, they might be persons of other persuasions,
and not Quakers, and I could not be capable of judging whether they were right or wrong.
It was not long before one stood up, and I thought to take good notice of what he said,
but so many wandering thoughts prevailed, that I got no benefit thereby.
He sat down, and in a little time another stood up, and I said to myself, Well,
I resolve I will mind what this man says;
but it was only a few minutes before my wandering thoughts got into Holland,
and from there I thought of going to France;
but meeting with a secret check in myself for these vain imaginations,
I gave a stamp upon the floor with my foot,
which caused the eyes of those in the meeting to be upon me:
so in fervency of spirit I said in myself,
"`What is the matter that I cannot be master over my own mind?`"

I saw I was altogether wrong,
and lacked inward strength to help me to get to a stayedness of mind upon God.
I was made sensible that there was a spiritual warfare to be passed through,
and that no stayedness of mind could be attained to,
till the inward enemies of the soul came to be destroyed.
I now saw my business was, to get into inward retirement,
hoping thereby I might get to be somewhat master over my own mind.
Being thus closely engaged, before the meeting broke up,
I got to a sight of the possibility of obtaining what I was then deeply engaged for,
and this answered the end of my coming to the meeting;
and I could then have wished that it would hold longer.

But it breaking up, when I came into Westminster-abbey-yard,
I met with some of my old acquaintance, who would have had me go along with them,
but I denied their invitation, finding I had another work to do,
and went home to my quarters, where I had not been long,
before the young man my companion also came in.
I was sitting in a very solid frame of mind, such as he never observed me in before,
and he said, "`Where have you been today, you seem to be so serious?`"
I proceeded to give him an account of what I had met with,
and reminded him of the temper I was in at the reading of my mother`'s letter.
"`Aye,`" said he, "`I saw you were under some dissatisfaction, but I knew not for what.`"
"`Why,`" said I, "`it was for my mother`'s desiring me to go to the Quakers`' meeting,
which begot such anger in me, that I had not patience to read it through: but this day,
walking in Coventgarden,
a sweet visitation from the love of God brought such a calmness over my mind,
with this attending it.
'`What is the matter that you cannot read your mother`'s letter?`'
I then plucked it out of my pocket and read it with pleasure.`"
And giving him the whole relation of what passed, he was struck with admiration,
saying to me, he had never heard anything like it;
that it must be something supernatural,
or it never could have had such an effect upon you.
And he was so far reached and convinced,
that he soon after forsook his former profession, and joined himself to the Quakers.

My country master`'s brother, who came in company with us to London,
had been convinced some time before this,
and by what means he heard I was at Westminster meeting on first-day, I know not;
but in a few days he came to pay me a visit, and finding me grave and serious,
gave me an invitation to come to his quarters in Grub street, near to Cripplegate,
at the house of two good honest Friends; the invitation was very pleasing to me,
as was my company to him, and them to whom I came.

The next meeting I went to was, I think, the Peel,
where I met with our ancient Friend James Park;
and although I met with little or no benefit from those two that appeared at Westminster,
yet I thought his doctrine reached home to my condition.
I had some superfluity in my apparel, which became such a load to me,
that I thought I groaned under the weight of it; and finding I could wear it no longer,
after the meeting I stripped it off, and that gave me some ease.

Several young men who heard of the manner of my convincement,
I think through the young man`'s relation who was my companion,
were so reached and affected therewith, and seeing my grave and solid behaviour,
who they heard had been before very wild, that they came also to embrace the Truth;
so that I was made very early an instrument for the convincement of several.

I followed my business closely, yet frequented meetings,
where I still met with renewed refreshment,
and found myself much bettered by those good opportunities:
for the love of God was greatly towards me, and I felt a growth in it;
and the overflowing of it was at times such, that I was ready to think the work was done,
and the inward warfare nearly come to an end.
But, alas!
I found myself mistaken.

Going one day to a meeting at Gracechurch-street,
where were William Dewsbury and Charles Harris, the latter stood up,
exhorting Friends to faithfulness,
and to resolve to do nothing but what was agreeable to the Truth.
I took such notice of that, that I said in myself, "`Well,
I resolve to do nothing disagreeable to the Truth.`"
No sooner had that resolution passed my thoughts,
than I felt a check in myself and a sensible decay to my inward enjoyment,
which increased gradually upon me, so that in a short time I came to a considerable loss.
This I took as a permission of the Almighty to bring me more to the knowledge of myself.

In this state I continued some time, and my inward life decaying,
I was brought very low as to my inward enjoyments,
which I had been formerly so plentifully supplied with,
so that I began to grow a little careless, and the enemy stepped in with it, saying,
"`You are but young,
and this is the only time for you to take the pleasures of this world,
and when you are old,
you know now how to get to what you have been so
earnestly engaged to come to the knowledge of.`"
I continued for some time in an unconcernedness of mind,
by which I sustained so great a loss,
that if I saw the faces of any of my friends in the street, I endeavoured to avoid them,
for shame covered me, believing they knew what a loss I was come to.

But after a time my merciful Lord remembered me, and as I sat at work,
the word of the Lord came to me, "`This is your day,
harden not your heart;`" which so struck me that I trembled.
Upon this I soon removed, and got to my old friends George and Dorcas Lowe`'s,
who dwelt not far from Aldersgate.
Now my concern came to be so great,
through losing by my transgression what I had formerly enjoyed,
and I so lay under the judgments of God,
that if I did but let out my thoughts towards any liberty, no, if I did but smile,
I was inwardly reproved; so that I saw I had no way to take,
but to lie under the hand of God.

In this state my exercise was very great, my tongue is too short to express it,
and my pen to describe it; and the way to get to what I once enjoyed,
I found by experience to be very narrow.
For if I took a wrong step, either by word or a vain thought,
my inward instructor made it manifest that it did not belong to me,
I had something else to do.
Thus I continued for some time, being inwardly very poor and barren,
and often beseeching the Almighty,
that he would be pleased to favour me with a small ray from the Sun of Righteousness,
to comfort a little my afflicted spirit.
In this state of affliction the enemy was not lacking with his temptations,
to draw me into a belief, that the day of my visitation was over;
but having had a knowledge of the manner of his dealings with me before,
I now kept a strict watch against him in all those attempts.

In the midst of these afflictions and hard besetments,
I now and then met with some encouragement, being made sensible of some springs of life,
that helped me to believe that the Lord would not forsake me.
And in this mournful and retired way of life, I had some Divine openings,
by which it was manifested to me, that by being brought through these exercises,
I should be the better prepared in time to be helpful to others.

From this time I began to grow and increase in that which was good;
and feeling the clouds to disperse, that had been over my mind,
the weight of my oppression began to be gradually removed,
and I felt my spirits grow more easy.
Then my hunger and thirst after righteousness increased,
which gave me encouragement to hope that in time all would be well,
and I was so revived through it, that I said in myself.
It is good for me that I have been thus afflicted,
for now I know something of what it is to buy the Truth;
for it had cost me but little before this.

Some time after, John Tyson, a Friend who had been banished for his religion,
who dwelt near the Bull-and-mouth meetinghouse,
desired me to come to be the foreman in his shop, which I complied with,
upon a certain salary for four years, which term I continued with him,
and the Lord was with me,
and gave me an understanding to do everything honestly belonging to my place and station,
and all things prospered under my hand.
But being through multiplicity of business kept very close,
I had many times longing desires to get to a meeting,
and there with my Friends to sit down in a retired manner,
out of the hurry and cares of the things of this world,
for those opportunities were often greatly refreshing.

While in this service,
I went with some public Friends to some country meetings on first-days,
which I took more than a little pleasure in,
not only for the benefit I received of the meeting, but of a little country air,
being still glad of embracing those opportunities.
Lucretia Cook, an ancient woman Friend, who had a public testimony,
came to desire me to ride before her to Hendon meeting, which was then pretty large.
I did so, and in the meeting I was under no small concern,
and a trembling laid hold of me; and as soon as the Friend had concluded in prayer,
I was concerned to kneel down to supplicate the Lord, which had such an effect,
that many present were broken into tenderness; it was indeed a comfortable opportunity.

This opened my way to further service, and I began to be concerned to appear in public,
and there was a tender care in the elders over me,
who would often be dropping some seasonable cautions to me,
by which I was greatly benefitted.
