== Chapter III

An account of his visit to Friends in Ireland.

My Irish journey now falling pretty weightily upon me,
I found myself engaged to visit Friends`' meetings in Norfolk and some parts of Suffolk,
and pretty thoroughly in Essex; and after I was clear of my service there,
I returned again to Norwich; and everything being prepared for my journey into Ireland,
I set out in the beginning of the seventh month,
after having taken a solemn farewell of Friends at Norwich,
and went through the Isle of Ely into Huntingtonshire,
and from there into Northamptonshire, and to Warwick,
where I once more visited William Dewsbury;
and from there into Staffordshire and Cheshire, visiting meetings as I passed along.

I stayed but little with my friend Mary Lowe, and went to Frandley on a first-day;
from there to Warrington and Liverpool, where staying one night,
I went next morning on board,
and in twenty-four hours the ship cast anchor in the bay of Dublin,
where I arrived about the latter end of the seventh month, in the year 1682.

In this nation I travelled up and down in the work of the Gospel, and had good service,
many being convinced by means of my ministry.
At Antrim, a place of great profession, I had a meeting in the evening,
to which many came, and some with a design to oppose me.
The place was not large enough to contain the people,
which occasioned those without to be very noisy and turbulent,
some of the ruder sort pelting them with bits of dirt and turf, while I was preaching.
I made a full stop, which occasioned a general silence; and after a little time I said,
"`I understand this is a place of great profession of religion:
I am sorry to see so much irreligion as appears among you at this time,
through your rude behaviour.
It is not long since I came out of my native country,
and I think it will not be long before I return again,
and then what shall I say of you to your poor suffering brethren in England?`"
There was a dread upon me when I spoke these words, which also affected those present,
for many of them trembled, and their faces gathered paleness.
Upon which I advised them, "`if you have any regard to the reputation of religion,
then inquire after those that are the occasion of these disorders,
for such behaviour is base and scandalous.`"
And moreover I was moved to say, "`the time draws nigh,
that you will be blown away like the chaff before the summer threshing-floor,
and the place of your meeting will not be found.`"
After this, some cried out in a Scottish tone,
"`We be all shamed,`" and getting out of the house,
inquired after those that were the occasion of the disorders: some lads they beat,
of others who absconded they took the names; after which we had a solemn good meeting,
the lively sense of the love of God reached to the hearts of many present,
and the meeting ended well.

At this meeting a young man a Papist, and servant to William Wilkinson, was convinced,
as were many more elsewhere in the north and other parts.
I travelled through Ulster and several parts of Munster and Leinster,
where I had many meetings.
I departed from Dublin on the 14th of the ninth month,
and returned there again on the 25th of the first month, 1683.

After the conclusion of the following Half-year`'s meeting,
I intended to return to England,
and in order to it I sold my horse and prepared for the voyage,
but the wind proving contrary, I could not get off.
Besides this, I found some stop in myself, a further service being presented to my view;
to which I gave up, though contrary to my inclinations, namely:
It fell with some weight upon me to have a meeting at Tralee, in the county of Kerry,
where William Bingley had been.
Accordingly I set out from Dublin the 17th of the third month,
taking meetings in the way, and went to Cork, and from there to Tralee,
a journey of one hundred and fifty-eight miles, accompanied by John Hammond,
Thomas Wight and some others, and had a comfortable opportunity;
many hearts were tendered, the Lord`'s presence attending, and after the meeting ended,
the people withdrew in a solemn and peaceable manner.
P+++.+++ White, a man of note in the town, came and offered them his house to meet in,
which they kindly accepted, as also of his invitation to dine with him next day,
and we parted in much friendship.
After this I visited several meetings in Leinster province, and went to the north again.

As I was going from Antrim to the Grange,
I saw ten or twelve men upon the road walking in a very solitary manner,
and it arose in my heart, "`These are sheep having no shepherd.`"
When I came up to them, I slackened my pace, and queried of them, "`What news?`"
The men were startled at the question, and answered,
"`We know of none;`" continuing to go softly, I said, "`Are you going to a meeting?`"
They answered, "`Our minister is silenced; for orders are come down,
commanding all Dissenters not to assemble; so now we have no teacher.`"
This brought to my remembrance what I had been concerned to deliver as above,
at the evening meeting I had at Antrim, where I met with so much rudeness, namely:
that the time draws nigh,
that you will be blown away like chaff before the summer threshing-floor,
and the place of your meeting will not be found.
At this time all Dissenters, except Friends, had declined keeping up their meetings.

I proceeded to discourse with the men aforementioned, and said,
"`The hireling flees because he is a hireling, and cares not for the sheep;
as it is said, John 10:11-13;`" referring them to the text; further showing,
"`it is happy for those who are come to the knowledge
of that Teacher who cannot be removed into a corner.
God said he would teach his children himself;
and the children of the Lord are taught of the Lord.
And you may read in the first Epistle of John, chap.
ii. 27, '`The anointing which you have received of Him abides in you,
and you need not that any man teach you,
but as the same anointing teaches you of all things,`' etc.
And in Titus 2:11,13., '`The grace of God which brings salvation,
has appeared unto all men, teaching us,`'`" etc.
Here I directed them to the great heavenly School-master, who said, "`Learn of me,
for I am meek and lowly in heart; follow me, and you shall find rest unto your souls.`"
Thus I laboured to bring them from their hireling teachers,
to the teaching of God and Christ in themselves,
by which they might come to the knowledge of God, and walk in the ways of his salvation;
"`for a manifestation of the Spirit is given to every man to profit withal.`"
I advised them to turn their minds inward, and mind the secret operation of it,
which checks and reproves for bad words and actions; and as they turned to it,
they would find it would lead them into all Truth; with many more words to this effect.
They were well pleased with this discourse, declaring at our parting,
that they had never heard things so opened to them in their lives.

The number of miles I travelled in Ireland was one thousand seven hundred and forty-six;
the number of meetings I had there, exclusive of Dublin, was one hundred and eighty;
and in this service I spent one year, within a few days.

Having cleared myself of what service lay upon me in this kingdom,
I took leave of Friends in a very large and solemn meeting at Dublin,
where the Lord`'s blessed presence and power crowned the assembly,
to our mutual joy and satisfaction; it was indeed a very tendering opportunity,
and in great unity we parted.
Soon after I took shipping in Dublin bay,
and in twenty-two hours we cast anchor at Liverpool, and I got to my friend Mary Lowe`'s,
at Crude-hall, that day twelve-month that I left it;
and found she was but newly discharged from imprisonment,
having been confined about three months for the first offence upon the Act of banishment,
she refusing to take the oaths.

I stayed not long there before it came upon me to visit meetings in Lancashire,
and after I had cleared myself of what was before me there,
I came to Stockport in Cheshire, and had a meeting;
from there I went to Hugh Burges`'s in Styall, where my friend Mary Lowe,
with several others, met me; I then went to Joseph Endon`'s, in Bosley,
where we met with our friend John Gratton, it being the first time I had seen him,
and we had there a very comfortable meeting, the hearts of many being greatly tendered;
and it was also the first time I had been on that side of the county.
After having taken one or two more meetings, we returned to Crude-hall.

In the beginning of the ninth month we declared our intentions
of marriage to Friends of Frandley Monthly Meeting;
after which I soon set out for Norwich, our Friend Jeffery Alcock accompanying me,
that being then the place of my settlement.
Their Monthly Meeting being on the third fourth-day of the same month,
I took but a few meetings in my way,
and got there time enough to lay my intentions before the same; which being done,
I travelled into Suffolk, and had meetings at Beccles and Aldborough,
the place where I formerly met with very rough entertainment from a man,
whose wife was some time before convinced by me,
and who had threatened to kill me if I came there again.
He hearing that I was to be at the meeting, came in, greatly enraged,
to revenge himself upon me.
I was speaking when he came in, and making his way up to me, he pulled me down,
and gave me several very ill blows about my head and face, which raised swellings.
In executing his fury upon me he fell down, but recovering himself,
and attempting to pursue his revenge further upon me, a Friend whose name was John Mason,
who had accompanied my honourable friend Giles Barnardiston and me to the meeting,
observing it, laid hold of him to prevent his doing any more mischief,
and being a very strong man, held him so fast that he could not disengage himself,
and desiring to be set at liberty, and promising to go away peaceably,
the Friend let him go.

In the mean time his wife went out of the meeting undiscovered by him,
and he not finding her, came in again; I was then concerned in my testimony as before,
but he seeing my friend Mason standing up before me, did not venture to come up to me,
but after venting a volley of revengeful oaths against me, he withdrew;
after which we had a peaceable good meeting.
The good woman lived not long after,
through the horrid abuses that he committed upon her;
she kept steady to her testimony to the end,
and was beloved by Friends and others that were acquainted with her.

From hence we went to Woodbridge, and so to Ipswich,
and after having visited some other meetings,
I accompanied my good friend Giles Barnardiston to his habitation at Clare in Suffolk.
After passing through some meetings I made my way to Norwich; where,
according to the good order used among us,
I presented my intentions of marriage a second time, and all things being found clear,
I set out for Cheshire, and taking a few meetings by the way,
I reached Derbyshire Quarterly Meeting, which was held the 25th of the tenth month.
The next day I went home with John Gratton, stayed one night, and then came to Stockport,
and the day following to Crowton, where I met with my friend Mary Lowe.
On the 1st of the eleventh month we again presented our
intentions of marriage to Frandley Monthly Meeting,
where being left to our liberty,
we accomplished the same on the fifth-day following at Frandley,
being the 3rd of the same month.

A general meeting at Newton coming on soon after, we went to it,
and it being a suffering time for Friends in that county,
Sir Philip Egerton and Captain Needham, two justices of the peace,
came to break up the meeting.
I was at prayer when they came in, and they stood awhile silent;
then Captain Needham stepped up to me and commanded silence, which I not observing,
he first took my hat and threw it away,
then got hold of my cravat and pulled it in pieces.
I still continuing my address to Almighty God, for his Divine presence was among us,
he then struck me over my head with his cane,
with such violence as to raise several great swellings on my head,
and after that he kicked me down with his foot from off my knees.

After this, Friends rising from their knees and putting on their hats,
he broke several of their heads, so that the blood ran down.
Then Sir Philip cried, "`Brother, brother, let us prosecute the law upon them,
and not abuse them;`" and my wife stood up and said with a raised voice, "`Turks,
Heathens and Infidels, would scorn such practice.`"

Their intention was to tender us the oaths, and send us to prison,
but having no Bible with them,
they took down names to prosecute us on the Conventicle Act,
and I was fined twenty pounds, and others proportionably to their stations,
which was levied with great rigour.
Their rigorous proceedings were so noised about in that and neighbouring counties,
that they were ashamed of their conduct, and came no more to break up our meetings.

Not many days after,
my wife was taken with a warrant and committed to Chester
castle for the second offence upon the Act of banishment,
where she continued with many others until the spring Quarter Sessions at Chester,
and was then discharged.

In the year 1684, I went up to the Annual Meeting at London,
and Friends there being kept out of their meeting-houses,
held their meetings in the streets.

In the spring of 1685, I found it upon my mind to visit Friends in Lancashire,
Westmoreland and Cumberland; and coming to Penrith,
I heard that our friend Thomas Wilson lay dangerously ill, so I left my horse at Penrith,
and walked to pay him a visit, and found him in a very weak condition.
After a short stay I was moved in spirit to supplicate the Lord on his behalf,
and I received a gracious answer, that he should be restored again to health;
upon which I desired him not to be discouraged, for he should do well; and I told him,
"`I believed in a short time I will see you again in Cheshire;`"
and it was not long before it came to pass.

The next day I came from Penrith to Carlisle, and got to the Border Meeting on first-day,
where the Lord was pleased to give us a comfortable opportunity together.
Several of our Friends were prisoners at that time at Carlisle.
From there, passing through most of the meetings in Cumberland,
I came to Pardsay-cragg meeting, which was very large;
and as in the other meetings I had passed through, so in that,
the Lord greatly favoured us with his life-giving presence,
by which the hearts of many were tendered.

From there I crossed the water into Lancashire, and came to the house of Dr. Lower,
where I stayed one night, and went to Swarthmore, the seat of Margaret Fox,
and paying a visit to the family, I went next to Lancaster, and stayed a meeting there;
and taking a few more meetings in that county I came to Warrington,
and stayed one night at Roger Haydock`'s, and the next day home,
where I found all well to my great satisfaction.

In the year 1686,
our ancient Friend Isaac Ashton and I went to see how our brethren fared northwards,
and taking some meetings in the eastern parts of Lancashire,
we came to Sedburg in Yorkshire, where we had a blessed meeting;
and taking meetings in the Dales of Yorkshire, we came to Grayrig, and had there,
as in other meetings we passed through, a very seasonable opportunity.

From there, taking meetings by the way, we came to Yarm,
where the next evening we had a very large meeting; from there we went to Stockton,
in the bishopric of Durham, where we found a pretty large body of Friends,
and had a good and solid opportunity among them.
Returning from there into Yorkshire, we came to Whitby and Scarborough,
where we had large and good meetings.
From there we passed through Malton to York,
where in the afternoon we had a large meeting,
a great many of King James`' soldiers coming to it, who behaved themselves,
for some time after they came in, a little rudely in talking to one another;
but after awhile the Lord`'s power broke in among them,
so that many were greatly tendered and broken, and the meeting ended to the satisfaction,
I think, of all present.

From York we went to Leeds, and so to Halifax;
at both which meetings the Lord greatly favoured us.
There I parted with my friend Isaac Ashton, and making my way towards Manchester,
I got home.

In the year 1687, I and my wife went for London,
in company with Samuel Watson and several other Friends.
After the Yearly Meeting was over, we went for Essex,
and visited the greatest part of the meetings in that county,
which were generally very large.

From Essex we went into Suffolk, where we had several large and precious opportunities;
and taking meetings as we went, we came to Norwich, where we stayed some days,
and had several very good and comfortable meetings.
After having visited many meetings in the county of Norfolk,
we felt drawings in our minds towards home.

We set forwards to my brother Joshua`'s, at Mildenhall in Suffolk,
and had a large and precious good meeting there; from there to the Isle of Ely,
and so into Huntingtonshire, where having visited several meetings,
we passed through Wellingborough to Northampton,
at which places the Lord greatly favoured us with his blessed presence.

From there passing through part of Leicestershire, we came through Nottinghamshire,
to Robert Mellor`'s, at Whitehough, in Staffordshire, where we stayed all night;
in the morning we went to Leek, and so to Macclesfield, and from there home,
where we were gladly received: this was a satisfactory journey to us both.

In the year 1688, we removed from Crowton to Stockport;
this and the following year I stayed pretty much at home.

About the latter end of the year 1690,
having strong drawings in my mind to visit Friends at London,
and in some parts of the West of England; it was then a very cold time,
and the lanes between Stockport and Macclesfield so full of snow,
that they were not passable, and we were forced to make our way through the fields.
We got to Macclesfield, where we stayed that night:
James Dickenson being also for London, and hearing that I was set out,
came and overtook me at Macclesfield.

We travelled together, taking meetings as we went,
till we came to Banbury in Oxfordshire,
where we found a meeting of public Friends at the house of Richard Vivers:
we came seasonably to it, and had a very reviving and comfortable opportunity,
to the great satisfaction of that solid assembly.
To this place we had a very hard journey, the ways being very bad,
the snow and ice considerable, and cold winds attending it.

From hence we went to Ailsbury, Uxbridge and London; here I stayed some time,
and after I had cleared myself I set out for the west, and taking meetings as I went,
came to Southampton and Ringwood; then to Pool, and passing through the Isle of Purbeck,
I came to Weymouth, where we found the people in a great consternation,
they espying a great fleet of ships, supposed them to be French;
but having sent out a boat to discover what they were, upon the return of it,
to their great joy and satisfaction, it was found to be a fleet of English merchant-men,
under convoy of some men of war.
War had before been declared between France and England.

After a short stay here, I came to Yeovil and Bristol; where I stayed some days,
and had very large and comfortable meetings among Friends,
as indeed I had all along hitherto; Friends being generally glad to see me,
I having formerly visited those meetings;
and the Lord`'s presence and power attended me in my service.

From Bristol I went to Frenchay, Nailsworth and Gloucester; from there to Worcester,
Sturbridge, Woolverhampton and Stafford; and taking a meeting or two more by the way,
I came to Stockport, arriving there pretty early in the spring, in the year 1691,
where I found all well, and was received with joy.
This was a satisfactory journey;
for having discharged the duty which the Lord required of me,
I had peace and comfort therein.

Postscript.

Our worthy Friend could not be prevailed upon to bring down
his memoirs lower than in the foregoing account.
I believe he did not travel much for many years before his decease,
but was a constant attender of our Circular Meetings,
as also Quarterly and Monthly Meetings; in which he was of singular service,
and eminently gifted both for doctrine and discipline,
well knowing how to divide the word aright, and was indeed as a prince in our Israel.
