== Chapter II

After my four years service was accomplished, I quitted myself thereof,
and a Friend being inclined to set up in the like business in the same street,
he requested me to be an assistant to him, which I complied with,
but it continued not long;
for I felt drawings in my mind to visit some meetings in Hertfordshire.
After my return from thence, having met with good satisfaction in that journey,
it came upon me to go towards Bristol,
and I had the company of a young man from Haverill in Suffolk.

After we left Bristol we travelled into Somersetshire,
but he having some pressing occasion to go home, we parted:
I took my way towards Dorsetshire, and coming to Weymouth, had several meetings there;
went from thence to Pool, and so to Ringwood in Hampshire, where I had several meetings,
and four or five young people were convinced of the Truth.

I came from thence to Southampton, from whence,
after having had several good opportunities, I went to the Isle of Wight;
and after having had some meetings there, I returned to Southampton.
I found it then my place to go back again to Ringwood, where Friends,
and the young people newly convinced, very gladly received me.

After having a meeting there, it opened upon my mind to go to Leamington,
where were but a few of our Society; but a meeting being appointed several went with me,
and a considerable company of the town`'s people came to it, some of whom were Baptists.
After a pretty time of silence, I stood up and began to speak,
and the priest of the town came in with two young men.
He sat down just before me, stayed the meeting till I had done, and then said to me.
What you have said are good and wholesome words, and good for edification.
But you talk of the teachings of the Spirit of God;
how shall we come by the Spirit of God?
I said.
What art thou?
He answered, I am a minister of the Gospel.
What, said I, a minister of the Gospel, and ask, how we shall come by the Spirit of God?
He that hath not the Spirit of Christ is none of his;
and as many as are led by the Spirit of God, they are the sons of God.
Why, that is Scripture, said he.
Well, but you say, that you may live here without sin.
Didst thou hear me say so, said I. No, replied he,
but I have a little book in my study that does say.
That men may attain to a sinless state on this side the grave.
I queried of him, who wrote that book?
Why, said he, one of you Quakers, I think his name is Whitehead.
What doctrine, said I, dost thou preach to the people, is it to continue in,
or to come out of sin?
He answered, To come out of sin;
but to attain to a state of sinless perfection is impossible,
for all our righteousness is as filthy rags.
But I hope, said I, that thou wilt not say,
that the righteousness of God is as filthy rags.
No, says he, God forbid I should say so; but in many things we all sin.
That, replied I, is for want of coming to the one thing needful.
People, says he, we never read of the one thing needful in all our lives.
Didst thou never read, said I, that Christ told Martha, she was cumbered in much serving,
but Mary had chosen that good part, the one thing needful,
that should not be taken from her.
Why, said he, that is Scripture too, I had forgotten it.
Well, but, said he, Paul cried out, Oh! wretched man that I am!
Are you better than Paul?
Dost thou believe, said I, that Paul was a sinner, and a wretched one too,
when he wrote that evangelical Epistle to the Romans?
Or, that he could be so in his writing in the 24th verse of the seventh chapter,
when in the next verse but one, he says,
"`There is therefore now no condemnation to them which are in Christ Jesus,
who walk not after the flesh, but after the Spirit.
For the law of the Spirit of life in Christ Jesus,
hath made me free from the law of sin and death.`"
That is Scripture, said he.

After he had sat a little while.
Now, says he, I have something come into my mind, I think God has brought it to me;
"`He that saith he hath no sin, deceiveth himself, and the truth is not in him.`"
He then made a flourish, saying, I have you fast now, I care not for you,
nor all the Quakers in England.
I replied.
Thou art an old man,
I am very sorry to find that thou takes upon thee
to plead so much for the devil`'s kingdom.
I tell you, says he, I don`'t plead for the devil`'s kingdom.
Why, said I, thou pleads for nothing but sin; and all sin being of the devil,
and thou pleading for nothing but sin, must consequently be a pleader for the devil.
This, said he, is only a digression from the matter; I have you fast,
you can never answer me.
Didst thou ever read the verse before that, said I. Yes, said he, I believe I have,
but I have forgot it.
What is it?
Why, it is this, "`If we walk in the Light, as he is in the Light,
we have fellowship one with another, and the blood of Jesus Christ his Son,
cleanseth us from all sin.`"
But if we walk not in the Light, we lose the benefit of the blood of Christ.
If any should then say, He hath no sin, he deceiveth himself, and the truth is not in him.
The next verse is, "`If we confess our sins,
he is faithful and just to forgive us our sins,
and to cleanse us from all unrighteousness.`"
If, after this, any should say, "`We have not sinned, we make him a liar,
and his word is not in us.
Be not deceived, he that doth righteousness is righteous, even as He is righteous.
He that is born of God sinneth not, neither indeed can he, for his Seed remaineth in him,
and he cannot sin, because he is born of God.
But he that committeth sin, is of the devil.`"

I said to the priest.
Art not thou now ashamed to plead so much for sin, which is of the devil`'s kingdom?
I further queried of him.
Dost thou take money for preaching such doctrine as this,
preaching up the necessity of sinning to the people,
when they do that too much without thy encouraging them?
Upon which he got up and said.
Well, I will be gone; but I desired him to stay, and I told , him,
I would prove him to be a deceiver before the people present.
He answered, I will not stay upon your demand.
So away he went, after which the people settled, and we had a good opportunity,
and parted in peace.

I returned that night to Ringwood, from whence, after a little stay,
I took my way towards London, going by Southampton,
and I there met with our ancient Friend Thomas Robinson.
From thence we went together to Portsmouth, where we had a comfortable meeting;
and after some few meetings more we parted, he going to Surry and Sussex,
and I taking some meetings by the way, arrived safe at London.

After staying some days in London, William Bingley and I went into Kent,
passing by Canterbury to Dover, taking several meetings in our way,
and we had many blessed and comfortable opportunities to our great satisfaction.
We were at the Quarterly Meeting of that county, which was pretty large,
and things were managed with a great deal of calmness and wisdom.

From thence, some meetings being appointed for us, we visited them,
and came to Worminghurst in Sussex, the seat of William Penn;
where staying a night or two, my companion and I parted,
he going further into the country, but I took my way back directly for London.
After having visited several meetings there,
I found my health and strength much impaired;
and having some drawings in my mind towards Norwich, I set out,
and after taking several meetings by the way,
I got to it in a better state of health than when I left London,
and my dear mother received me there with a great deal of joy,
I not having seen her for several years.
The first meeting I was at there, was on a fourth-day,
which was indeed a very tendering opportunity, the hearts of many being greatly affected.
I found it now to be my place to take my abode there;
and in a short time after a great many of the younger
sort of people frequented the meeting,
and several were convinced; several Friends also had their mouths opened in testimony,
who grew to be very serviceable in their generation.

In the year 1677, I had some drawings in my mind to visit some parts of the North,
and going by Lynn, I took several meetings in Lincolnshire, till I came to Brigg,
but having got a severe cold, I there fell ill of a fever, which was so sharp upon me,
that several despaired of my life.
George Whitehead being then in the country, and hearing of my weakness, came to see me,
which I took very kindly, but my fever was not then at its height;
yet through the goodness of God I recovered sooner than could have been expected.

From thence I went to Hull, Thomas Markham accompanying me.
We had but a rough passage, and the night was dark;
but through some difficulty we arrived safe at the town,
where there being a great noise of a Popish plot against the king and government,
at our landing we found a strong guard set to examine all passengers,
but my friend that accompanied me being well known there, they let us pass peaceably.
Staying some few meetings there, my friend returned to Brigg, and I took my way to York,
visiting some meetings as I went.
My illness had brought me very low; but Friends gladly received me,
and I had several comfortable opportunities with them.
From thence I went to Leeds, taking Tadcaster in my way,
and although I was yet but weakly in body, the Lord`'s blessed presence did so attend me,
that in meetings I appeared as if I ailed nothing;
and I had many sweet and comfortable opportunities with Friends,
as I passed through that county.

From Leeds I went to Sheffield and Chesterfield; and had there a very good meeting.
And being very desirous to get to Nottingham meeting on first-day,
I stayed no meeting at Mansfield; but stayed at Nottingham some days,
at the house of our ancient Friend John Reckless, and had several good meetings there.
From thence I went to Leicester, where I found several Friends in prison, whom I visited,
and had a seasonable opportunity with them.
From Leicester I came to Northampton, and had a meeting,
in which the Lord`'s power broke in upon us; it was indeed a very tendering opportunity,
blessed be God for it.
After staying there two or three nights, I came to Wellingborough,
and having had a meeting there, I had drawings in my mind towards Banbury.
I was now attended with a tertian ague,
and the winter coming on made the fits more tedious to me.
Coming to Banbury, I lodged at the house of Richard Vivers,
who finding me in so weak a condition, took great care of me,
so that in a few days I was finely revived, and went to Oxford,
and had a good and peaceable opportunity there.

From thence I returned to Banbury, and after having had a few meetings thereabouts,
I went through some part of Bedfordshire into Hertfordshire;
having meetings there as I passed along.
I came into Essex; but my disease growing more strong upon me,
and the weather being sharp, and my natural strength being much impaired,
I made my way towards Norwich, where, by short journeys, I arrived in the eleventh month,
and found Friends well, and meetings very well frequented.
My ague continued several months after,
and I grew so weak that many despaired of my recovery.
But the spring coming on, I began to recruit in strength,
and was enabled to visit several meetings in the county.
When I was at home I was not idle, but worked at my trade very diligently,
and was also a constant frequenter of our first and weekday meetings.
The next spring, in the year 1679, I went up to London,
and after the Yearly Meeting was over, visited some meetings in Essex and Suffolk,
and got home in health,
having had many sweet and comfortable opportunities to mine and Friends`' mutual satisfaction.

Although things had been at a low ebb for several years in the city of Norwich,
as to the growth and prosperity of Truth,
yet now the hearts of many were opened to receive the testimony of it,
and they joined with and sat down amongst us,
and their gravity and sobriety gained them a good report amongst the people;
by which several who were strangers to us came also to be convinced,
and received the Truth, joining themselves to our Society.
We were now straitened for room where the meeting was kept;
and there being a piece of ground that Friends had formerly purchased,
we began to talk of building a meeting-house there,
which the younger sort of Friends were zealously concerned
for--but there not being many wealthy men amongst us,
although they were sensible that such a place was wanting,
they began to consult how money could be raised to answer the occasion.
Upon this, those that were of the best abilities made subscriptions,
and finding they fell short of the required sum,
before Friends could be got to enlarge their former subscriptions,
they began to call upon the younger sort, who as yet had subscribed nothing,
to know what they would do towards carrying on the work.

All being sensible of the necessity for such a place,
they needed not many words to stir them up to subscribe out of their small abilities,
most of them being journeymen combers, weavers, shoemakers, etc.,
but they were desired not to put down more than what they
would take care honestly to pay when called upon.
So they began to consider how much they could earn in a week,
and how much of that they could lay by towards the forwarding of so good a work;
upon which we found that a handsome sum would be raised.
This gave such encouragement to the former subscribers,
that they agreed with the workmen to erect such a building as was proposed to them.

This intention of Friends soon got abroad in the city,
and some of the leading men thereof, particularly the recorder, gave out.
That the Quakers never should build a house there;
but Friends took no notice of his threats, but laid the foundation of the house.
Several of the younger Friends took a view of it,
and believing it would not be large enough to answer the occasion,
desired the workmen to stop till further orders:
upon which they had recourse to the first subscribers,
some of whom subscribed ten pounds a piece more;
but that still falling short to make good the intended enlargement,
the poorer sort were again called upon to know what they would contribute further?
And they found the Lord so blessed their endeavours,
that they could contribute more than they thought they could when they subscribed before,
and so they advanced above their first proposal.
And for a further enlargement thereto,
the young men made application to the young women servants, etc.,
desiring them to exert themselves upon this occasion, which they readily did,
and raised several pounds amongst themselves.
The work went readily on, and was finished to the satisfaction of all concerned.

But the recorder breathed out further threatenings, saying,
although the Quakers had built the house, they should never meet in it.
Yet when everything was finished, we had our first meeting there on a fourth-day,
in the year 1680, which was large and comfortable,
for the Lord`'s blessed presence was among us, and we parted peaceably.
The first-day following we met again in the morning,
which meeting also ended in peace to our great satisfaction.
In the afternoon the meeting was much larger,
but towards the conclusion thereof came the recorder, with the priest of the parish,
and several officers, soldiers and others.
I was at prayer when they came in, and the recorder and the priest stepped upon a seat,
and there stood till I had almost done; then the recorder cried out.
Silence there.
When I arose from my knees, he asked me my name, and what trade I was of,
and then ordered the constables to take me out into the passage that goes to the street,
and then went on taking the names of Friends present;
but the priest was quickly weary of staying, for several told him.
It ill became him to appear there,
to encourage a spirit of persecution against his peaceable neighbours.
The recorder replied.
You meet in contempt of the law.
He was answered,
that we looked upon it as our indispensable duty to meet together
to perform that worship which we owe to Almighty God,
and that we were no disturbance to the government, being peaceably met together,
of which they themselves were witnesses.
The parson quickly withdrew and went into the street,
but having stood there awhile he came in again, and stepping up to me, said.
You are a stubborn people, and might prevent all this trouble if you would come to church.
Pointing to the steeple-house, I said.
What, dost thou call that the church?
He said, Yes, it is a church; if it be not a church, what is a church?
I say it is the church.
I answered.
The church of God is the pillar and ground of Truth.
You talk, said he; if I ask you one question of Divinity, you cannot answer me a word.
I answered.
How dost thou know that, thou hast not yet tried me;
and he went away into the meeting again without any reply.
He had not stayed long there until he came out again,
and there being several people in the passage, he began to tell them,
The Quakers were an erroneous people, they deny baptism and the Lord`'s Supper.
I stepped up to him, and laid my hand upon his shoulder and said,
Thou asserts what thou canst never prove.
Oh, said he, are you there?
And so went into the street, and staying till the recorder came out,
they walked away together.

Two Friends in the meeting having observed the recorder`'s rigorous proceedings,
reminded him of the illegal proceedings of Empson and Dudley;
at which he took such offence, that after he had done taking names,
he made their mittimus and sent them to prison, where, I think,
they were confined till discharged by the following Quarter Sessions.
I expected likewise to be committed,
being kept all this time under a guard in the passage; but when the recorder came out,
he looked upon me, yet said nothing, but passed away, which the guard observing,
they also passed away, and left me at liberty.
Not long after this our ancient Friends, George Whitehead and Thomas Burr,
came to Norwich, and being at our meeting on a first-day,
were taken up and carried before the recorder before-mentioned, who,
upon their refusal to pay twenty pounds a man for preaching,
tendered them the oath of allegiance, which they also refusing,
he committed them to prison.

I was at this time visiting some meetings in the country,
but after my return to the city, going to our week-day meeting, the constable,
one Paul Hartley, an envious malicious man, came to the meeting,
and finding me at prayer, took me before the recorder,
and I expected no other but to be committed; but he appeared pretty mild,
only asking me my name and place of abode, etc., which I told him.
The busy constable took upon him to say.
Sir, there is an act by which you may commit him; whereupon I told him,
he seemed to be a very bold man, to take upon him to tell the recorder what he might do;
which the recorder smiled at, and after a few words told me, I was at liberty,
and might go about my business.

At this time our meetings began to be pretty much attended with informers,
and the sufferings of Friends increased, and soon after,
as I was at prayer in the afternoon meeting, the constable and informers came in,
and took me before the mayor, and I was at his house before he came from his worship;
there came with him the sheriff and several aldermen.
At his first appearance he seemed very rough; I said little to him,
but he presently went up into his council chamber with his attendants,
and after awhile he sent for me, the constable and informers, to come up.
He then inquired of the constable, where he found me?
who told him, at the Quakers meeting.
He inquired what I was doing, and the informers answered, Sir,
he was speaking to the people.
Upon which the mayor asked me my name, which I told him; he then asked me,
What trade I was of?
I told him I was a shoemaker.
Oh! said he, these are brave times, when shoemakers,
weavers and combers set up to be preachers.
I told him,
I thought that a shoemaker was not much inferior to a fisherman or a tent-maker,
yet we find Christ called such, and made them able ministers,
which I hoped he would not deny.
Oh! said he, they were moved to it by the Spirit of God.
Yes, said I, and the same God yet is.
Aye, but, said he, that extraordinary way is not now to be expected.
I answered, that he now, that hath not the Spirit of Christ is none of his;
and so many as are led by the Spirit of God, they are the sons of God.

There was a Divine dread attended me upon this occasion,
and I was sensible that the power of Truth was over all,
through which I took the freedom to advise them, to take heed what they did,
lest haply they should be found fighting against God; and that he,
and those that were present, knew us to be an industrious and peaceable people,
and to persecute us for our meeting together to worship God,
which we looked upon to be our indispensable duty,
and to impoverish us to gratify a parcel of indigent informers,
I thought would not tend much to their honour.
Why, says the mayor, you can call them indigent informers,
but you refuse to give persons their due titles.
I told him, I thought he was mistaken,
for we never refused to give persons their due titles, as mayor, alderman, sheriff, etc.
Well, said he, I am glad to hear it;
and then called to his servant to bring up a bottle of wine, which was done,
and a glass being filled, he said to me, here is to you, but you shall not drink,
and so gave it to the sheriff; and when the rest had drank, he said.
However, I will give him a glass, which I refused; he again desired me to take it,
and I still refusing it, it caused him to look a little blank.

Upon this they all went down, and taking their leave of the mayor, left me alone with him.
He then appeared very loving and friendly to me,
desiring me to take no exceptions at his rough behaviour at first; for, said he,
times so run, that I am obliged to show my dislike to such things,
that otherwise I should not incline to do;
and he also asked me whither I inclined to go from thence?
I told him, to a friend of ours that lived in Dow lane;
and he looking out and observing a multitude of people in the market-place,
who met to see what became of me, for fear they should give me any disturbance,
there being four of the sheriff`'s officers at hand,
he ordered them to attend me whither I had a mind to go; which they accordingly did.
When the people saw me guarded by four men, they concluded I was going to prison,
my way from the mayor`'s lying towards it, at which they seemed to be sorry;
but seeing me turn down Dow lane, they appeared to be glad of it,
and when I came to my friend`'s door, my guards took leave of me in a friendly manner.

Having for a considerable time had some drawings in my mind
to get a meeting in a little sea-port called Cloy,
not far from Wells, and there being but one Friend in town, who was a master of a ship,
I could not well tell how to obtain it; but he coming to town, I acquainted him thereof.
He told me he was glad of it,
and did not at all doubt but he could manage that point to my satisfaction; for, said he,
my father is living, and his dependency is partly upon me,
so that he will hardly refuse anything that I request of him,
and he is clerk of the parish, and as soon as I have discoursed him,
and find a way opened, I will acquaint thee therewith.
Accordingly he did so, and a meeting was appointed, which he advised me of,
and thither I went, and there was a considerable appearance of people,
both of the town and country, and a good peaceable meeting we had,
for the Lord`'s blessed presence was amongst us, blessed be his name for it;
when I had concluded in prayer, the old clerk said Amen heartily.

I concluding to stay there all night, a supper was prepared for me,
and the priest of the town hearing of the meeting, was inclined to discourse with me,
but not being willing to undertake it himself,
he sent about three miles to another priest to come to his assistance, which he did.
As soon as it began to grow a little dark and they were coming, the young man,
the Friend, went to see after my horse, but meeting them pretty near to the house,
he turned in again, and told me there were two priests coming.
Upon this notice I sunk down to my life, and kept very retired, and they came in,
and after taking a turn or two about the house,
the assistant came and sat down pretty near me, I having been pretty warm in the meeting,
had my cloak on, which I then commonly rode in.
The town priest still walking about, I arose and said to him.
If thou pleasest thou mayst sit down here.
The word thou greatly displeased him.
His assistant said, You may keep your seat, we are plain men,
and are come to you without a cloak.
With that I turned to my seat and replied, If you be plain men, it is well,
and though you come to me without a cloak, yet, let me tell you,
your covering is blacker than mine.
How do you mean, says he?
I replied, I mean as I say.
What, says the town priest, is this their preacher?
Yes, says the other, I challenge him to be him.

By this time a great many people came into the house,
and stood about the door and windows.
The assistant then said.
We are come to dispute with you, and you shall lay down your proposition,
and we will dispute upon it.
I told him, it looked unfair in them, they being two,
to press me to lay down a proposition, which was not the practice of fair disputants;
but the assistant pressed it several times.
I then told them, I was there, and if they had anything to object against me,
I was ready to answer for myself.
No, said they, we have nothing to charge you with,
but you must lay down your proposition, and we will argue thereupon.
Something now opening upon my mind, I told them,
that although it looked very unfair in them, yet if I laid down a proposition,
would they answer me?
They both said, Yes, they would.
Then, said I, "`There is a manifestation of the Spirit of God given to every man,
to profit withal; this Spirit of God is the Spirit of Truth,
and that so many as give up to it, to be led and guided by it,
it would lead and guide them into all Truth.`"
This is my proposition, and I will stand by it.

The town priest in a scornful manner said, This is no more than what we own;
and made a great noise up and down the house.
Upon which I said, I have something more to say to it; but he continuing his noise,
the other priest said to him.
Sir, pray hear him, he says, he has something more to say to it.
Upon this he was silent.
And I said, since what I have laid down is no more than what you own, I query,
Are you the men that are so given up to it,
as to be led and guided by the Spirit of Truth, into all Truth, yea or nay?
The town priest said, I thought what he would say; and the other replied, Sir,
it is to the matter in hand.
And he then said to me, I perceive you are a scholar, pray tell me what university,
and what college you were educated in?
I said, you did promise here, before the people, that you would answer me,
and I insist upon it; but no answer I could get.
But the town priest in a light, airy spirit, said.
You Quakers pretend to be led by the Spirit of God; did the Spirit lead you to this town?
I arose up and told him, I take thee to be a man not worth a word,
but if thou wilt be quiet (he continuing to make a noise) I will answer thee.
He replied, methinks you are very bold.
Yes, said I, my cause is very good.
Well, said he, what have you to say?
I answered, it was upon me from the Lord to visit that place.
How shall I know that, said he?
I answered, whether thou knowest it or no, the fruits of my labour shall make it manifest.
Did you ever hear the like, people, said he, I have talked with him all this while,
and he has not convinced me yet.
Oh! vain man, said I. Notwithstanding the singular life, the excellent doctrine,
and unparalleled miracles which our blessed Lord wrought,
the high priests were so far from being convinced by him,
that they took an occasion the more to put him to death.
Upon which he was silenced.

Now, says I, as thou asked me a question, How came here?
in my turn, I ask thee, how thou camest here?
He answered, Why, the Lord placed me here.
What to do, said I? He answered, To be an overseer, and a worker in his vineyard.
Aye, said I, I shall soon know that; the apostle says, when he was sent forth,
it was to unstop the deaf ear, and to turn people from darkness unto light,
and from the power of Satan unto God.
Now, said I, how many hast thou turned since thou camest to this place?

There standing a chair between us, he thumped with his hand upon it, and said,
May be God`'s time is not yet come.
What, said I, did God place thee here to do no good?
And since thou canst not make it appear that thou hast converted one soul,
in turning it from darkness to light, and from Satan`'s power to God;
if thou wouldst prove thyself to be an honest man,
I would advise thee to make a return of the money
or effects thou hast received from the people.
And, people, said I, I would have you to require it of him;
for by his own discourse he cannot say, that he has done you any good.
Well, said the priest, I will be gone.
No, said I, I would have thee stay,
and I will undertake to prove thee a deceiver before the people.
I will not stay, said he, upon your demand, and away he went.

His assistant sat all this while and said nothing; but now, when the other was gone,
I turned to him and asked him, what he had now to say?
He answered, You are the honestest people that dissent from the church,
in the whole kingdom, and I love you the best.
Ah! said I, this is of the colour of thy cloth, and it looks very black;
thou camest in a light, airy spirit, and now thou begins to flatter us.
Nay, replied he, I speak the truth, and you shall come to visit me; I live at Holt,
says he, three miles off, and you must not deny me.
Well, said I, if thou art inclinable,
and willing to allow any sober-minded people to be present,
I don`'t know but I may answer thy request.
No, said he, there shall be nobody present but you, and Robert Kirby, and me,
and we will not have a word of religion, but only on school terms.
If that be all, said I, I think I shall not come.
Well, said he, I must be going, and he went out, and I went with him;
and as we were walking on the sea-shore, This, said he, I have observed,
that if once any come to be joined to your Society,
they may as well wash a blackmoor white, and cleanse a leopard from his spots,
as turn any of you from your persuasion.
I answered, we could get nothing that did us any good, when amongst you,
and having met with the Word of eternal life, whither should we go?
There are many of you, continued I, that are men of learning and good education,
and did you wait to receive power from God,
you might be serviceable and do good to the people.
Well, said he, you say well; but I must go, and he took me by the hand and said,
I wish you well.
I wished him the same, and so we parted.

The young man above-mentioned, some time after told me,
that my service at Cloy had such an effect,
that some who had the opportunity of the meeting,
and of hearing what had passed with the clergy in the evening,
were so thoroughly convinced, that they joined themselves to our Society; and the clerk,
his father, not living long after, confessed to the Truth upon his dying-bed.

Pretty early in the spring, in the year 1681,
it was upon me to go into some part of the west;
so about the latter end of the first month I left Norwich,
and had my first meeting at Wells, where I had a blessed opportunity;
from thence I went to Holt, and so to North Walsham and Yarmouth.
After which I went to Beckles in Suffolk; from thence to Aldborough,
Woodbridge and Ipswich; and taking a few meetings more in this county,
I passed into Essex; where having stayed some weeks visiting meetings,
I came well to London, and stayed there until the Yearly Meeting was over.

Then leaving London I came to Kingston, and some who were at that meeting,
told me some years after, what benefit they had received from my being there,
and they were thankful to the Lord for it.
From thence I took some meetings in my way to Alton, where was a large and good meeting;
from thence to Southampton, and after a short stay there, to Ringwood,
where I was gladly received, several having been convinced at my former being there.
I stayed there some meetings to the mutual comfort and satisfaction of Friends and others.

From Ringwood I went to Pool, and so to the isle of Purbeck,
where I had a meeting at a public inn, to which many people resorted,
and I had a good and serviceable opportunity, many things convincingly opening in me,
suitable to the states of several that were present.
I passed from thence to Weymouth, where I found myself engaged to stay several meetings;
for there was an open door,
and many received the testimony of truth with gladness in that place.

From Weymouth I returned again to Ringwood, taking meetings in my way;
I stayed there but a little,
and took leave of Friends in the spirit of love and divine fellowship,
and taking some few meetings in my way, I went to Marlborough,
and had a good opportunity.
And visiting some other meetings, I came to Reading, where we had a comfortable meeting,
the Lord`'s blessed presence being sensibly felt, to the joy and comfort of many present.
Taking some meetings as I went, I got again to London; and stayed but little there,
for I felt a concern upon my spirit to visit some parts of the north,
and took not many meetings before I got to Norwich.

In this journey I can truly say, a spring of Divine Goodness did attend me,
and the meetings through which I passed, were sensible partakers thereof,
and comforted thereby.
Whilst I stayed in the city, I followed my business very closely;
but my journey before mentioned, falling more weightily upon me,
I found I could not be clear without giving up to answer it, whereupon I prepared for it,
and accordingly, towards the latter end of the seventh month I set forward,
and taking some meetings, passed through the isle of Ely into Huntingtonshire;
after having had several meetings in that county,
I came to Wellingborough in Northamptonshire, and so to Northampton.

From Northampton I had drawings in my mind to go to Warwick,
to visit our friend William Dewsbury, who was then a prisoner there,
whom I was very glad to see, and he took my visit very kindly.
After having had several meetings in that county, my way opened to go to Worcester;
and having stayed some meetings there, I came next into Herefordshire,
taking meetings as I passed along through that county into Radnorshire.
I got to Welch Pool, and having had a meeting there, I went for Shrewsbury,
and stayed a meeting there.
From thence I went to a meeting appointed for me at Gilbert Woollam`'s, at Ranmore,
near Namptwich in Cheshire, to which then a pretty many substantial Friends belonged;
but many of them afterwards removing into Pennsylvania, did greatly lessen it.
I lodged that night with our ancient Friend Thomas Briggs,
often mentioned in George Fox`'s Journal; and the good old man told me in the morning,
he had been much concerned that night in praying
to the Lord for the whole society of his people.

The next day I went to John Simcock`'s at Rigley-hall,
where I had a meeting that evening, and was at Malpas meeting the next day.
From thence I went to Chester, where I had a meeting on a sixth-day;
on the seventh-day I came to Crude-hall.
On the first-day following I had a meeting at Newton by the Forrest,
which was large and comfortable; the third-day following I had another at Sutton,
and returned that night to Crude-hall,
where was a Friend who had a concern for a considerable
time to go a little northward to visit Friends,
and took the opportunity and went with me.
After visiting Frandley meeting, we went to Warrington in Lancashire,
and had a meeting at William Barns`'s in Sankey, on the first-day;
whose house being too straight for the meeting,
I persuaded Friends to get a meeting-house built, which they readily fell in with,
and the next day met, and made subscriptions in order thereto.
And the building was soon after got up,
which did much better accommodate the Friends of the meeting.

From thence we went to Manchester, which meeting was then small;
we travelled from thence to Rossendale,
where we had a good opportunity at the burial of a Friend;
and after taking several meetings by the way, we got to Lancaster,
and in the way thither had many heart-tendering opportunities,
the Lord`'s blessed presence and power greatly attending us in our service.
We had there a good meeting.
Then passing the Sands we came to Swarthmore.

We had here a very solid opportunity, for the Lord`'s living presence was amongst us,
and in a sense thereof we departed and came to Hawkshead; from thence we went to Kendal,
where we had a pretty large and good meeting.
After having had meetings at Crook, and some other places in Westmoreland,
we came into Yorkshire, and visiting several meetings in that county, came to Settle,
where my friend and I parted, after having had many comfortable opportunities,
and great satisfaction in our labours and travels in the service of Truth.

I went towards York, taking Skipton, and several other meetings in my way thither.
Staying some meetings there, I went to Malton, and so to Scarborough,
where I stayed some time.
I had my health pretty well, although much weakened as to my natural strength;
a fresh visitation of the spring of life overflowing my soul, supported me,
and thereby the hard labours and travels I passed through,
were made much more easy to me, as well as comfortable to those I visited;
for which I was truly thankful to the Lord; blessed be his name for it.

Next I went to Burlington, and taking a meeting or two by the way I got to Hull.
I was much comforted hitherto; and taking a meeting a few miles from Hull,
on the river Humber, I went over in the passage-boat,
there being one appointed for me on the other side, and found Friends met together,
and had a good meeting amongst them; as I also had in the preceding.
The next was at Brigg, where Friends were glad to see me,
and I had a comfortable meeting with them.

I pursued my way to Gedney, had a meeting there, and went directly for Lynn in Norfolk,
and staying a few days there, I went afterwards to Fakenhara, and from thence to Norwich,
where Friends received me with joy.
I got thither about the beginning of the twelfth month.
In this journey I was greatly favoured, the Lord`'s presence attending me all along;
blessed be his name.

Some time after as I was going to a meeting in the country,
Ireland was presented to my view, and there being a Friend with me that had been there,
I inquired of him, what kind of a country Ireland was?
At the expressing of which words a trembling seized me; which he observing, said,
I believe it will be thy place to go thither.
I took no notice of that,
nor did I mention my concern to any body for a considerable time: but it grew upon me,
and I found I could not be clear without giving up to it;
and mentioning it to some Friends, the knowledge of it quickly got abroad to many.

The Yearly Meeting drawing on, I went directly to Colchester, and from thence to London,
where I met Roger Haydock and his wife, and my friend Mary Lowe.
Here I imparted my mind to her, which,
although we had often met together before in our journeys,
I never so much as mentioned to her;
though my spirit was closely united in a Divine fellowship with her.

After the meeting was over, Roger Haydock went for the west, Mary Lowe accompanying him,
and his wife returned home.
I stayed not long after in the city, but Colchester Yearly Meeting drawing on,
and Isabel Yeamans, daughter of Margaret Fox, having it in her mind to go thither,
and desiring my company, I went to it with her.
After our service was over there, we went to Ely, to visit our friend Samuel Cater,
who was then a prisoner there.

From thence we travelled to Norwich, where my friend had several good opportunities;
and visiting some adjacent meetings, she returned again to Norwich;
from whence we went to Colne,
where some Friends from London met her to accompany her thither, and there we parted.

Taking some meetings from thence in my way home, I came to Haverill in Suffolk;
and Daniel Gridley`'s wife having it upon her mind to visit some meetings in Norfolk,
went along with me to Norwich; and being at the morning meeting,
whilst concerned in prayer, one of the informers with a constable came in,
and when she had done, he carried her to the mayor`'s house,
who was not then come from his worship; but so soon as he came in,
being told by the constable the reason of his being there,
the mayor desired him to go to the next justice of the peace,
the earl of Yarmouth being to dine with him that day, which he accordingly did.

At our first appearance the justice was very rough,
and talked of making her mittimus to send her to jail,
because she was found speaking in the Quakers`' meeting-house.
I told him, she was brought before him through the information of an informer;
and the Act they proceeded upon was a fining, but not an imprisoning act.
Upon that he called for the statute book, and finding it to be so,
he then inquired her name, and from whence she came, and told her,
she had better have stayed at home,
than come there to have her husband fined twenty pounds for her preaching.
I desired him to consider, that as she was not preaching but praying,
her devotion was to God in prayer, which the Act doth not forbid;
and it would be unreasonable to set a fine upon her for that.
Besides, said I, the Act requires two witnesses, and here is but one.
Why, says he, here is the constable, he can be a witness.
I hope, said I, thou wilt not make the constable an informer.
No, said the constable, I have done my office, but I will not turn informer.
Upon this the justice said, I think you study more to evade the law,
than you do your prayers to please God.
I told him, we were a suffering people,
and it greatly concerned us to consult the laws we were prosecuted upon,
and he not having had a hand in that work before, that I knew of,
he might be unacquainted with the said laws; to which he answered.
This is the first person that has been brought before me upon this account.
I thereupon told him, that if he pleased to consider of it until the next morning,
I believed my friend would promise, and I would engage with her,
to appear before him if he required it.
Well, said he, we will leave it then, you promising to appear if I send for you.
She said.
Yes, I will, if God permit: upon which we withdrew.

In the afternoon the said Friend had a good opportunity in the meeting,
and it broke up peaceably.
The next morning, not hearing any thing from the justice, two or three of our Friends,
besides myself, who were well known to him, went to his house,
and as soon as we appeared before him, he looked upon me with an angry countenance,
saying, I am informed you are a Jesuit; upon which the Friends smiling, told the justice,
that whosoever had given him that information were greatly mistaken,
for they knew me to be otherwise, and that I was born in that county,
and then lived in that city.

After which he talked with us more freely,
and signified that it was no pleasure to him to persecute his religious neighbours,
and as this was the first that came before him on that account,
he hoped it would be the last.
Then we requesting to know his pleasure,
whether the Friend who had been with him should come before him again:
after some little more discourse he told us, she might go about her business;
which we told him we took as a favour from him, and so departed.
And after she had visited several more meetings in the county,
she returned towards her habitation, being well satisfied with her journey.
