== A Testimony from the Quarterly Meeting of Cheshire

Held at Newton, near Middlewich, the 9th of the twelfth month, 1741,
concerning our dear and worthy Friend and elder in the Truth, Benjamin Bangs, deceased.

This our ancient honourable Friend and eminent minister of Jesus Christ,
was born in the parish of Longham, in the county of Norfolk,
the 1st day of the tenth month, 1652, of reputable parents,
and was religiously educated in the principles of the Church of England, so called,
by his mother, his father dying when he was young.
The Lord was pleased in his young and tender years
to extend a merciful visitation of love to him,
with which he was at times deeply affected; and about the nineteenth year of his age,
being then settled in London, he was convinced of the blessed Truth, as professed by us,
and in a short time after came forth in a public testimony,
and became an able minister of the Gospel of Christ,
in which he laboured faithfully and fervently in divers parts of this nation,
and in the kingdom of Ireland, before he came to settle amongst us,
and was instrumental in the convincement of many.

In the year 1683, he married our worthy Friend Mary Lowe, of this county,
and settled amongst us;
after which he visited many parts of this nation and the Principality of Wales,
and even until age and infirmities prevailed,
continued to visit the meetings of Friends in this and the adjacent counties,
where his services were always acceptable.

He was an elder worthy of double honour, having obtained a good report,
not seeking glory of men, nor lording it over God`'s heritage,
but as an ensample to the flock, not forward to appear in public service;
in doctrine sound, clear, instructive and uncorrupted;
his openings were fresh and lively, and his manner of expression excellent.
He delighted much to wait in silence for the pure openings of the word of life,
whereby he became strong in the Lord and in the power of his might,
sounding forth the word of reconciliation by Christ our Lord,
and salvation through his eternal Spirit;
and was often fervent in prayer and supplication,
and drawn forth in a sweet and heavenly manner, to the joy of the sincere in heart.
He was signally qualified in our Monthly and Quarterly Meetings,
to speak a word in season for the promotion of peace,
good order and discipline in the church;
which meetings he constantly attended when at home and in health.

He was remarkably compassionate to the poor of the Society,
in whom he observed a degree of sincerity and worthiness,
who were sure to meet with an advocate in him.

In his private capacity, his countenance was solid, his deportment grave,
but intermixed with a pleasant and familiar manner of expression,
that rendered his company pleasant to all with whom he conversed.
And even when old age and infirmities attended, his understanding was clear,
and many sweet and heavenly expressions dropped from him,
concerning the largeness of the love of God to his soul,
together with seasonable advices, to the tendering of the hearts of those present.

He often said to this purpose, that his work was finished, and he freely resigned,
feeling nothing but peace from the Lord upon his spirit; yea,
so plentifully was it poured forth upon him, that when near his end,
he could not forbear rejoicing in the blessed experience thereof, saying,
"`Now I know and witness the saying of our blessed Lord fulfilled,`" viz:
"`He that believeth in me, out of his belly shall flow rivers of living water.`"

Much more might be said concerning this good man,
and his services and labours in the work of the Gospel for many years,
which are so well known to many, that we need not enlarge thereon.
And although his removal from us is a loss to the church,
yet we fully believe it is his everlasting gain,
he being gathered home into the garner of God, as a shock of corn fully ripe,
there to enjoy the blessed reward of the righteous
in an endless fruition of joy and glory.
As he lived, so he died, a servant of the Lord and his people,
on the 6th day of the twelfth month, and was decently buried the 9th of the same,
in Friends`' burying-ground in Stockport, in the year 1741,
in the ninetieth year of his age, and was a minister about sixty-five years.
